# DO NOT EDIT THIS FILE!
#
# Python module pdfservice__POA generated by omniidl

import sys
import os

# Ensure parent directory is in path for importing stubs
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import omniORB
omniORB.updateModule("pdfservice__POA")

# ** 1. Stub files contributing to this module
try:
    import ConversionService_idl
except ImportError as e:
    print(f"Warning: Could not import ConversionService_idl in pdfservice__POA: {e}", file=sys.stderr)
    print(f"Looking for stubs in: {parent_dir}", file=sys.stderr)
    print(f"Python path: {sys.path}", file=sys.stderr)
    raise
import ConversionService_idl

# ** 2. Sub-modules

# ** 3. End
